# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 17:50
from __future__ import unicode_literals

from django.db import migrations
from movieratings.worker import add_movie_data

class Migration(migrations.Migration):

    dependencies = [
        ('movieratings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_movie_data)
    ]
