# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieratings', '0002_auto_20160609_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avg_Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_raters', models.IntegerField()),
                ('average_rating', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieratings.Movie')),
            ],
        ),
    ]
