# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieratings', '0003_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avg_rating',
            name='average_rating',
            field=models.FloatField(),
        ),
    ]
