# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieratings', '0004_auto_20160611_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avg_rating',
            old_name='count_raters',
            new_name='count_ratings',
        ),
    ]
